-- DROP DATABASE IF EXISTS db_php;
-- CREATE DATABASE db_php;
USE db_php;

DROP TABLE IF EXISTS blob_mailing;

CREATE TABLE IF NOT EXISTS blob_mailing(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  file MEDIUMBLOB NOT NULL,
  dating TIMESTAMP DEFAULT NOW()
);